adapter: mysql2
  encoding: utf8
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: SuperD
  password: SuperD
  socket: /var/run/mysqld/mysqld.sock

development:
  <<: *default
  database: superd_dev
